<?php

/**
 * @file
 * Module file for Islandora Object Clone.
 */

/**
 * Implements hook_menu().
 */
function islandora_object_clone_menu() {
  $items = array();
  $items['admin/islandora/tools/object_clone'] = array(
    'title' => 'Object Clone',
    'description' => 'Configure Islandora Object Clone.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('islandora_object_clone_admin_form'),
    'file' => 'includes/admin.form.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['islandora/object/%islandora_object/clone'] = array(
    'title' => 'Clone',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_object_clone_confirm_form'),
    'file' => 'includes/confirm.form.inc',
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'islandora_object_clone_access_callback',
    'access arguments' => array(
      array(
        ISLANDORA_MANAGE_PROPERTIES,
        ISLANDORA_METADATA_EDIT,
        ISLANDORA_ADD_DS,
        ISLANDORA_PURGE,
        ISLANDORA_INGEST,
      ), 2),
  );
  return $items;
}

/**
 * Checks whether the user can access the given object's 'Clone' tab.
 *
 * @param array $perms
 *   Array of user permission to test for.
 * @param AbstractObject $object
 *   The object to test, if NULL given the object doesn't exist or is
 *   inaccessible.
 *
 * @return bool
 *   TRUE if the user is allowed to access this object, FALSE otherwise.
 */
function islandora_object_clone_access_callback($perms, $object = NULL) {
  module_load_include('inc', 'islandora_object_clone', 'includes/utilities');
  $object_models = $object->models;
  $allowed_models = variable_get('islandora_object_clone_allowed_cmodels', array());
  $allowed_models_filtered = array();
  foreach ($allowed_models as $key => $value) {
    if ($value != '0') {
      $allowed_models_filtered[] = $value;
    }
  }
  $intersection = array_intersect($object_models, $allowed_models_filtered);

  $sequence_free = islandora_object_clone_is_sequence_free($object);

  if ($sequence_free && islandora_object_manage_access_callback($perms, $object) && count($intersection) > 0) {
    return TRUE;
  }
}
